# Generated by Django 5.0.7 on 2025-03-31 16:15

import django.core.validators
import promotions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('description', models.TextField(default='', verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed', 'Số tiền cố định')], default='percentage', max_length=10, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá trị giảm')),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá trị đơn hàng tối thiểu')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giảm giá tối đa')),
                ('valid_from', models.DateTimeField(verbose_name='Có hiệu lực từ')),
                ('valid_to', models.DateTimeField(default=promotions.models.get_default_valid_to, verbose_name='Có hiệu lực đến')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn hiệu lực')),
                ('usage_limit', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giới hạn sử dụng')),
                ('times_used', models.IntegerField(default=0, verbose_name='Số lần đã sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
            },
        ),
    ]
