"""
Django settings for dstore project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
from decouple import config
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'b9ad-42-115-245-215.ngrok-free.app']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Bắt buộc cho Django Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',  # Hỗ trợ đăng nhập Google, Facebook
    'allauth.socialaccount.providers.google',  # Nếu muốn đăng nhập bằng Google
    'allauth.socialaccount.providers.facebook',  # Nếu muốn đăng nhập bằng Facebook
    #Custom application
    'core',
    'userauths',
    'products',
    'orders',
    'cart',
    'promotions',
    'shipping',
    'imports', 
    'checkout',
    'dashboard',
    'django_ckeditor_5',
    'pages',
    'slider',
    'django.contrib.humanize',
    'favorites', 
]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middlewares.SeparateSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'dstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_context',
                'products.context_processors.menu_context',
                'products.context_processors.global_brands',
            ],
        },
    },
]
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                   'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
        'height': '300px',
    },
}

# Add media path for CKEditor 5
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
CKEDITOR_5_UPLOAD_PATH = "uploads/"
WSGI_APPLICATION = 'dstore.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': 'SET character_set_connection=utf8mb4;'
                          'SET character_set_client=utf8mb4;'
                          'SET character_set_database=utf8mb4;'
                          'SET character_set_results=utf8mb4;'
                          'SET character_set_server=utf8mb4;'
                          'SET collation_connection=utf8mb4_unicode_ci;'
                          'SET collation_server=utf8mb4_unicode_ci;'
                          'SET time_zone = "+07:00";'
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    'site_title': 'Dstore Admin',
    'site_brand': "Dstore",
    'site_logo': "assets/images/logos/DStore.png",
    "welcome_sign": "Welcome to the Dstore Admin",
    'copyright': "dstore.com",
    "search_model": ["auth.User", "auth.Group"],
    "user_avatar": None,
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],
    "use_google_fonts_cdn": True,
    "order_with_respect_to": ["dashboard", "auth", "core", "userauths", "products", "orders"],
    "icons": {
        "dashboard.Dashboard": "fas fa-chart-line",
    }
}

AUTH_USER_MODEL = 'userauths.User'

AUTHENTICATION_BACKENDS = [
    'userauths.auth_backends.EmailOrUsernameBackend',
    'userauths.auth_backends.CustomSocialAuthBackend',
]
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],  # Yêu cầu quyền truy cập profile & email
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'picture'
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'vi_VN',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    }
}

ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True  # Cho phép tự động tạo tài khoản khi đăng nhập lần đầu

LOGIN_REDIRECT_URL = "/"  # Điều hướng sau khi đăng nhập thành công
LOGOUT_REDIRECT_URL = "/admin/login/?next=/admin/"  # Điều hướng sau khi đăng xuất


# Tự động liên kết tài khoản Google/Facebook với tài khoản đã có email trùng khớp
SOCIALACCOUNT_ADAPTER = "allauth.socialaccount.adapter.DefaultSocialAccountAdapter"
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"

CSRF_COOKIE_SECURE = False  # Chỉ cần True nếu bạn đang sử dụng HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Địa chỉ SMTP của Gmail
EMAIL_PORT = 587  # Cổng SMTP cho TLS
EMAIL_USE_TLS = True  # Sử dụng TLS
EMAIL_HOST_USER = '@gmail.com'  # Địa chỉ email của bạn
EMAIL_HOST_PASSWORD = ''  # Mật khẩu ứng dụng hoặc mật khẩu của bạn
DEFAULT_FROM_EMAIL = '@gmail.com'  # Địa chỉ email gửi đi

VNPAY_TMN_CODE = 'LRWA2UKH'
VNPAY_HASH_SECRET_KEY = 'RZLD3MQNT3ECWPNU2WXINORNV2B0AO38'
VNPAY_PAYMENT_URL = 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'

# MoMo Test Environment Settings
MOMO_PARTNER_CODE = 'MOMOBKUN20180529'
MOMO_ACCESS_KEY = 'klm05TvNBzhg7h7j'
MOMO_SECRET_KEY = 'at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa'
MOMO_API_ENDPOINT = 'https://test-payment.momo.vn/v2/gateway/api/create'
MOMO_RETURN_URL = 'http://localhost:8000/checkout/momo-return/'
MOMO_NOTIFY_URL = 'http://localhost:8000/checkout/momo-notify/'

SESSION_COOKIE_NAME = "user_sessionid"
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 86400  # 1 ngày
SESSION_EXPIRE_AT_BROWSER_CLOSE = False