# Generated by Django 5.0.7 on 2025-04-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_favoriteitem_favorites_f_user_id_5f0886_idx_and_more'),
    ]

    operations = [
    ]
