# Generated by Django 5.0.7 on 2025-04-11 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Đơn nhập hàng',
                'verbose_name_plural': 'Đơn nhập hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('import_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imports.importorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn nhập',
                'verbose_name_plural': 'Chi tiết đơn nhập',
            },
        ),
    ]
