# Generated by Django 5.0.7 on 2025-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Tiêu đề phụ')),
                ('button_text', models.CharField(max_length=50, verbose_name='Nút bấm')),
                ('button_link', models.CharField(max_length=200, verbose_name='Đường dẫn')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Hình ảnh')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['order'],
            },
        ),
    ]
