# Generated by Django 5.0.7 on 2025-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Tiêu đề phụ')),
                ('title_start', models.CharField(blank=True, max_length=100, verbose_name='Phần đầu tiêu đề')),
                ('title_highlighted', models.CharField(blank=True, max_length=100, verbose_name='Phần tiêu đề nổi bật')),
                ('title_end', models.CharField(blank=True, max_length=100, verbose_name='Phần cuối tiêu đề')),
                ('button_text', models.CharField(max_length=50, verbose_name='Nút bấm')),
                ('button_link', models.CharField(max_length=200, verbose_name='Đường dẫn')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Hình ảnh')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('show_year', models.BooleanField(default=False, verbose_name='Hiển thị năm')),
            ],
            options={
                'verbose_name': 'Slide Trang Chủ',
                'verbose_name_plural': 'Slides Trang Chủ',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
