# Generated by Django 5.0.7 on 2025-04-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_homeslide_delete_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instagram/', verbose_name='Hình ảnh')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Mô tả ảnh')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ảnh Instagram',
                'verbose_name_plural': 'Ảnh Instagram',
                'ordering': ['order'],
            },
        ),
    ]
