# Generated by Django 5.0.7 on 2025-04-07 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shipping', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao thành công'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản ngân hàng'), ('vnpay', 'VNPAY'), ('momo', 'MOMO')], default='cod', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vnpay_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('momo_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('shipping_name', models.CharField(max_length=255, null=True)),
                ('shipping_email', models.EmailField(max_length=254, null=True)),
                ('shipping_phone', models.CharField(max_length=20, null=True)),
                ('shipping_address', models.TextField(default='Unknown Address')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.city')),
                ('shipping_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.district')),
                ('shipping_ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.ward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('promotions', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('product_id', models.IntegerField(default=0)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_color', to='products.colortype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_size', to='products.size')),
            ],
        ),
    ]
