# Generated by Django 5.0.7 on 2025-04-06 20:32

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên thương hiệu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('brand_types', models.CharField(blank=True, default='1', help_text='Chọn các loại phù hợp, phân cách bằng dấu phẩy (vd: 1,2)', max_length=50, null=True, verbose_name='Loại thương hiệu')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('category_type', models.CharField(choices=[('1', 'Nam'), ('2', 'Nữ'), ('3', 'Trẻ em')], default='1', max_length=50, verbose_name='Loại danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='ColorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Màu sắc')),
                ('code', models.CharField(default='#000000', help_text='Ví dụ: #FF0000', max_length=50, verbose_name='Mã màu')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Chất liệu')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kiểu giày')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Kích cỡ')),
            ],
        ),
        migrations.CreateModel(
            name='UsePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mục đích sử dụng')),
                ('purpose_types', models.CharField(help_text='Chọn các loại phù hợp, phân cách bằng dấu phẩy (vd: 1,2)', max_length=50, verbose_name='Loại mục đích')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá khuyến mãi')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Giá nhập')),
                ('stock', models.IntegerField(verbose_name='Tồn kho')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path, verbose_name='Hình ảnh')),
                ('product_code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Mã sản phẩm')),
                ('labels', models.CharField(blank=True, choices=[('sale', 'Sale'), ('hot', 'Hot'), ('new', 'New')], max_length=10, null=True, verbose_name='Nhãn')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Thương hiệu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Danh mục')),
                ('colors', models.ManyToManyField(blank=True, to='products.colortype', verbose_name='Màu sắc')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.material', verbose_name='Chất liệu')),
                ('shoe_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shoetype', verbose_name='Loại giày')),
                ('sizes', models.ManyToManyField(blank=True, to='products.size', verbose_name='Kích cỡ')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhà cung cấp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('brands', models.ManyToManyField(blank=True, to='products.brand', verbose_name='Thương hiệu')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.usepurpose', verbose_name='Mục đích sử dụng'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Đánh giá')),
                ('comment', models.TextField(default='No comment provided', verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProductSizeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_inventory', to='products.product', verbose_name='Sản phẩm')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='Kích cỡ')),
            ],
            options={
                'verbose_name': 'Tồn kho theo size',
                'verbose_name_plural': 'Tồn kho theo size',
                'unique_together': {('product', 'size')},
            },
        ),
    ]
